# docker file for gateway service
FROM golang:1.22.4-alpine AS builder

WORKDIR /app

COPY ./gateway .

RUN go mod download

RUN go build -o main .

FROM alpine:latest  

WORKDIR /root/

COPY --from=builder /app/main .

EXPOSE 8000

CMD ["./main"]