version: "3.9"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15-alpine
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -p 5435 -d auth"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./.misc:/.misc # for transferring files like .sql imports
    networks:
      - mynetwork
volumes:
  cockroach-data:

networks:
  mynetwork:
